// <auto-generated />
using CafeteriaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeteriaMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeteriaMVC.Models.Inter_ItemUsuario", b =>
                {
                    b.Property<int>("Inter_ItemUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inter_ItemUsuarioID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Inter_ItemUsuarioID")
                        .HasName("PK__Inter_It__5172E7B6EF58EE29");

                    b.HasIndex("ItemID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Inter_ItemUsuario");
                });

            modelBuilder.Entity("CafeteriaMVC.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.HasKey("ItemID")
                        .HasName("PK__Item__727E83EB21E04C67");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("CafeteriaMVC.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<byte[]>("Senha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.HasKey("UsuarioID")
                        .HasName("PK__Usuario__2B3DE798BC46B99B");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__A9D10534C7A82BC2")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CafeteriaMVC.Models.Inter_ItemUsuario", b =>
                {
                    b.HasOne("CafeteriaMVC.Models.Item", "Item")
                        .WithMany("Inter_ItemUsuario")
                        .HasForeignKey("ItemID")
                        .IsRequired()
                        .HasConstraintName("FK_Inter_Item");

                    b.HasOne("CafeteriaMVC.Models.Usuario", "Usuario")
                        .WithMany("Inter_ItemUsuario")
                        .HasForeignKey("UsuarioID")
                        .IsRequired()
                        .HasConstraintName("FK_Inter_Usuario");

                    b.Navigation("Item");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CafeteriaMVC.Models.Item", b =>
                {
                    b.Navigation("Inter_ItemUsuario");
                });

            modelBuilder.Entity("CafeteriaMVC.Models.Usuario", b =>
                {
                    b.Navigation("Inter_ItemUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
